source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'
use_frameworks!

target 'ImageSlideshow_Example' do
    pod "ImageSlideshow", :path => "../"
    pod "ImageSlideshow/AFURL", :path => "../"
    pod "ImageSlideshow/Alamofire", :path => "../"
    pod "ImageSlideshow/SDWebImage", :path => "../"
end
