source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'
use_frameworks!

target 'DPImageSlideshow_Example' do
    pod "DPImageSlideshow", :path => "../"
    pod "DPImageSlideshow/AFURL", :path => "../"
    pod "DPImageSlideshow/Alamofire", :path => "../"
    pod "DPImageSlideshow/SDWebImage", :path => "../"
end
